import { Animation } from "@primodiumxyz/engine";

export const AnimationConfig: Animation[] = [
  /* --------------------------------- Sprites -------------------------------- */
  {
    key: "hex/holo",
    assetKey: "sprite-atlas",
    randomFrame: true,
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/hex/holo/Holo_Rough_",
    suffix: ".png",
  },
  {
    key: "pending/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/blue/Pending_Blue_",
    suffix: ".png",
  },
  {
    key: "pending/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/green/Pending_Green_",
    suffix: ".png",
  },
  {
    key: "pending/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/red/Pending_Red_",
    suffix: ".png",
  },
  {
    key: "magnet/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/blue/Magnet_Blue_",
    suffix: ".png",
  },
  {
    key: "magnet/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/green/Magnet_Green_",
    suffix: ".png",
  },
  {
    key: "magnet/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/red/Magnet_Red_",
    suffix: ".png",
  },
  {
    key: "shield-eater/idle",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    repeat: -1,
    prefix: "sprites/shield-eater/idle/ShieldEater_Test_Idle_",
    suffix: ".png",
  },
  /* ----------------------------------- VFX ---------------------------------- */
  {
    key: "conquer/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/blue/Conquer_Blue_",
    suffix: ".png",
  },
  {
    key: "conquer/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/green/Conquer_Green_",
    suffix: ".png",
  },
  {
    key: "conquer/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/red/Conquer_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/red/upper/Arc_Upper_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/green/upper/Arc_Upper_Green_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    zeroPad: 3,
    endFrame: 19,
    prefix: "vfx/destroyer/blue/upper/Arc_Upper_Blue_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    zeroPad: 3,
    endFrame: 19,
    prefix: "vfx/destroyer/red/lower/Arc_Lower_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/green/lower/Arc_Lower_Green_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/blue/lower/Arc_Lower_Blue_",
    suffix: ".png",
  },
  {
    key: "waves",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 31,
    randomFrame: true,
    repeat: -1,
    prefix: "vfx/waves/Magnet_Waves_",
    suffix: ".png",
  },
  {
    key: "overheat/low",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    randomFrame: true,
    repeat: -1,
    prefix: "vfx/overheat/low/Overheat_Low_",
    suffix: ".png",
  },
  {
    key: "overheat/medium",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    randomFrame: true,
    repeat: -1,
    prefix: "vfx/overheat/medium/Overheat_Medium_",
    suffix: ".png",
  },
  {
    key: "overheat/full",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    randomFrame: true,
    repeat: -1,
    prefix: "vfx/overheat/full/Overheat_Full_",
    suffix: ".png",
  },
  {
    key: "shield-eater/detonate",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/shield-eater/detonate/ShieldEater_Test_Shaking_",
    suffix: ".png",
  },
  {
    key: "shield-eater/crack",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    randomFrame: true,
    zeroPad: 3,
    prefix: "vfx/shield-eater/crack/AOE_Crack_",
    suffix: ".png",
  },
];
