import { Animation } from "@primodiumxyz/engine";

export const AnimationConfig: Animation[] = [
  /* --------------------------------- Sprites -------------------------------- */
  {
    key: "hex/holo",
    assetKey: "sprite-atlas",
    randomFrame: true,
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/hex/holo/Holo_Rough_",
    suffix: ".png",
  },
  {
    key: "pending/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/blue/Pending_Blue_",
    suffix: ".png",
  },
  {
    key: "pending/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/green/Pending_Green_",
    suffix: ".png",
  },
  {
    key: "pending/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/red/Pending_Red_",
    suffix: ".png",
  },
  {
    key: "magnet/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 8,
    repeat: -1,
    prefix: "sprites/magnets/blue/Magnet_Blue_",
    suffix: ".png",
  },
  {
    key: "magnet/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 8,
    repeat: -1,
    prefix: "sprites/magnets/green/Magnet_Green_",
    suffix: ".png",
  },
  {
    key: "magnet/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 8,
    repeat: -1,
    prefix: "sprites/magnets/red/Magnet_Red_",
    suffix: ".png",
  },
  /* ----------------------------------- VFX ---------------------------------- */
  {
    key: "conquer/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/blue/Conquer_Blue_",
    suffix: ".png",
  },
  {
    key: "conquer/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/green/Conquer_Green_",
    suffix: ".png",
  },
  {
    key: "conquer/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/red/Conquer_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/red/upper/Arc_Upper_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/green/upper/Arc_Upper_Green_",
    suffix: ".png",
  },
  {
    key: "destroyer/upper/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    zeroPad: 3,
    endFrame: 19,
    prefix: "vfx/destroyer/blue/upper/Arc_Upper_Blue_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    zeroPad: 3,
    endFrame: 19,
    prefix: "vfx/destroyer/red/lower/Arc_Lower_Red_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/green/lower/Arc_Lower_Green_",
    suffix: ".png",
  },
  {
    key: "destroyer/lower/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 19,
    prefix: "vfx/destroyer/blue/lower/Arc_Lower_Blue_",
    suffix: ".png",
  },
];
