import { Animation } from "@primodiumxyz/engine";

export const AnimationConfig: Animation[] = [
  /* --------------------------------- Sprites -------------------------------- */
  {
    key: "hex/holo",
    assetKey: "sprite-atlas",
    randomFrame: true,
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/hex/holo/Holo_Rough_",
    suffix: ".png",
  },
  {
    key: "pending/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/blue/Pending_Blue_",
    suffix: ".png",
  },
  {
    key: "pending/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/green/Pending_Green_",
    suffix: ".png",
  },
  {
    key: "pending/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/red/Pending_Red_",
    suffix: ".png",
  },
  {
    key: "pending/yellow",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/yellow/Pending_Yellow_",
    suffix: ".png",
  },
  {
    key: "pending/pink",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/pink/Pending_Pink_",
    suffix: ".png",
  },

  {
    key: "pending/purple",
    assetKey: "sprite-atlas",
    frameRate: 10,
    randomFrame: true,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/pending-arrows/purple/Pending_Purple_",
    suffix: ".png",
  },
  {
    key: "magnet/blue",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/blue/Magnet_Blue_",
    suffix: ".png",
  },
  {
    key: "magnet/green",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/green/Magnet_Green_",
    suffix: ".png",
  },
  {
    key: "magnet/red",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 7,
    repeat: 0,
    prefix: "sprites/magnet/red/Magnet_Red_",
    suffix: ".png",
  },
  {
    key: "magnet/yellow",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 8,
    repeat: 0,
    prefix: "sprites/magnet/yellow/Magnet_Yellow",
    suffix: ".png",
  },
  {
    key: "magnet/pink",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 8,
    repeat: 0,
    prefix: "sprites/magnet/pink/Magnet_Pink",
    suffix: ".png",
  },
  {
    key: "magnet/purple",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 8,
    repeat: 0,
    prefix: "sprites/magnet/purple/Magnet_Purple",
    suffix: ".png",
  },
  {
    key: "shield-eater/idle",
    assetKey: "sprite-atlas",
    frameRate: 8,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/shield-eater/idle/ShieldEater_Idle_",
    suffix: ".png",
  },
  {
    key: "shield-eater/enter",
    assetKey: "sprite-atlas",
    frameRate: 8,
    startFrame: 0,
    endFrame: 13,
    prefix: "sprites/shield-eater/enter/ShieldEater_Enter_",
    suffix: ".png",
  },
  {
    key: "shield-eater/exit",
    assetKey: "sprite-atlas",
    frameRate: 8,
    startFrame: 0,
    endFrame: 15,
    prefix: "sprites/shield-eater/exit/ShieldEater_Leave_",
    suffix: ".png",
  },
  {
    key: "shield-eater/detonate",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "sprites/shield-eater/detonate/ShieldEater_Detonate_",
    suffix: ".png",
  },
  {
    key: "shield-eater/target",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 12,
    randomFrame: true,
    repeat: -1,
    prefix: "sprites/shield-eater/target/Shield_Target_",
    suffix: ".png",
  },
  {
    key: "shield-eater/crack",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 3,
    prefix: "sprites/shield-eater/crack/Cracks_",
    suffix: ".png",
  },
  {
    key: "citadel/crown",
    assetKey: "sprite-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    repeat: 0,
    prefix: "sprites/citadel/crown/Citadel_Crown_",
    suffix: ".png",
  },
  {
    key: "planet/treasure/large",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/planet/treasure/large/Planets_Iridium_",
    suffix: ".png",
  },
  {
    key: "planet/treasure/medium",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/planet/treasure/medium/Planets_Iridium_Medium_",
    suffix: ".png",
  },
  {
    key: "acid-rain/enter/large",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 4,
    prefix: "sprites/acid-rain/enter/large/AcidRain_Enter_",
    suffix: ".png",
  },
  {
    key: "acid-rain/enter/medium",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 0,
    prefix: "sprites/acid-rain/enter/medium/AcidRain_Enter_Medium_",
    suffix: ".png",
  },
  {
    key: "acid-rain/enter/small",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 0,
    prefix: "sprites/acid-rain/enter/small/AcidRain_Enter_Small_",
    suffix: ".png",
  },
  {
    key: "acid-rain/exit",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 3,
    prefix: "sprites/acid-rain/exit/AcidRain_Fade_",
    suffix: ".png",
  },
  {
    key: "acid-rain/idle/large",
    assetKey: "sprite-atlas",
    frameRate: 3,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/acid-rain/idle/large/AcidRain_Large_",
    suffix: ".png",
  },
  {
    key: "acid-rain/idle/medium",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/acid-rain/idle/medium/AcidRain_Medium_",
    suffix: ".png",
  },
  {
    key: "acid-rain/idle/small",
    assetKey: "sprite-atlas",
    frameRate: 3,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/acid-rain/idle/small/AcidRain_Small_",
    suffix: ".png",
  },

  /* ----------------------------------- VFX ---------------------------------- */
  {
    key: "conquer/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/blue/Conquer_Blue_",
    suffix: ".png",
  },
  {
    key: "conquer/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/green/Conquer_Green_",
    suffix: ".png",
  },
  {
    key: "conquer/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/red/Conquer_Red_",
    suffix: ".png",
  },
  {
    key: "conquer/yellow",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/yellow/Conquer_Yellow_",
    suffix: ".png",
  },
  {
    key: "conquer/pink",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/pink/Conquer_Pink_",
    suffix: ".png",
  },
  {
    key: "conquer/purple",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 14,
    prefix: "vfx/conquer/purple/Conquer_Purple_",
    suffix: ".png",
  },

  {
    key: "movement/red",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/red/Movement_Red",
    suffix: ".png",
  },
  {
    key: "movement/green",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/green/Movement_Green",
    suffix: ".png",
  },
  {
    key: "movement/blue",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/blue/Movement_Blue",
    suffix: ".png",
  },
  {
    key: "movement/yellow",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/yellow/Movement_Yellow",
    suffix: ".png",
  },
  {
    key: "movement/pink",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/pink/Movement_Pink",
    suffix: ".png",
  },
  {
    key: "movement/purple",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 1,
    endFrame: 14,
    prefix: "vfx/movement/purple/Movement_Purple",
    suffix: ".png",
  },
  {
    key: "combat",
    assetKey: "vfx-atlas",
    frameRate: 8,
    startFrame: 0,
    endFrame: 16,
    prefix: "vfx/combat/Combat_",
    suffix: ".png",
  },
  {
    key: "waves",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 31,
    randomFrame: true,
    repeat: -1,
    prefix: "vfx/waves/Magnet_Waves_",
    suffix: ".png",
  },
  {
    key: "citadel/shine",
    assetKey: "vfx-atlas",
    frameRate: 10,
    startFrame: 0,
    endFrame: 9,
    prefix: "vfx/citadel/Citadel_Shine_",
    suffix: ".png",
  },
  {
    key: "iridium/add",
    assetKey: "vfx-atlas",
    frameRate: 8,
    startFrame: 0,
    endFrame: 11,
    prefix: "vfx/add-iridium/Add_Iridium_",
    suffix: ".png",
  },
];
