[profile.default]
solc_version = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 10
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.caldera]
eth_rpc_url = "https://primodium-bedrock.calderachain.xyz/replica-http"
chain_id = 12523

[profile.caldera-sepolia]
eth_rpc_url = "https://primodium-sepolia.rpc.caldera.xyz/http"
chain_id = 10017

[profile.base-sepolia]
# eth_rpc_url = "https://base-sepolia.g.alchemy.com/v2/r7XIy5ha8oVNDTsTaYoZ7VVZ-hcbNRam"
eth_rpc_url = "https://sepolia.base.org"
chain_id = 84532

[profile.redstone-holesky]
eth_rpc_url = "https://rpc.holesky.redstone.xyz"
chain_id = 17001

[invariant]
runs = 4
depth = 32768
fail_on_revert = false
